"""
"""

from enum import StrEnum


class MedicalCondition(StrEnum):
    NONE = "NONE"

    PCOS = "PCOS"
    ENDOMETRIOSIS = "ENDOMETRIOSIS"
    UTERINE_FIBROIDS = "UTERINE_FIBROIDS"
    ADENOMYOSIS = "ADENOMYOSIS"
    OVARIAN_CYST = "OVARIAN_CYST"
    MENSTRUAL_DISORDER = "MENSTRUAL_DISORDER"
    AMENORRHEA = "AMENORRHEA"
    DYSMENORRHEA = "DYSMENORRHEA"
    ABNORMAL_UTERINE_BLEEDING = "ABNORMAL_UTERINE_BLEEDING"
    PELVIC_INFLAMMATORY_DISEASE = "PELVIC_INFLAMMATORY_DISEASE"
    VAGINITIS = "VAGINITIS"
    CERVICITIS = "CERVICITIS"
    INFERTILITY = "INFERTILITY"
    MENOPAUSAL_SYMPTOMS = "MENOPAUSAL_SYMPTOMS"

    NORMAL_PREGNANCY = "NORMAL_PREGNANCY"
    HIGH_RISK_PREGNANCY = "HIGH_RISK_PREGNANCY"
    GESTATIONAL_DIABETES = "GESTATIONAL_DIABETES"
    GESTATIONAL_HYPERTENSION = "GESTATIONAL_HYPERTENSION"
    PREECLAMPSIA = "PREECLAMPSIA"
    ECLAMPSIA = "ECLAMPSIA"
    PLACENTA_PREVIA = "PLACENTA_PREVIA"
    PRETERM_LABOR = "PRETERM_LABOR"
    MULTIPLE_PREGNANCY = "MULTIPLE_PREGNANCY"
    INTRAUTERINE_GROWTH_RESTRICTION = "INTRAUTERINE_GROWTH_RESTRICTION"
    POST_TERM_PREGNANCY = "POST_TERM_PREGNANCY"
    HYPEREMESIS_GRAVIDARUM = "HYPEREMESIS_GRAVIDARUM"

